### ISSUE TITLE
Italics?

### ISSUE THREAD

**Issue by litera** [macduy/FiraCousine#1]
Cousine font has a nice italic set as well and I do use italics in comments to distinguish them more from the rest of running code. Would there be a chance that you would add italics as well? They may as well be just normal Cousine italics without ligatures as long as they are renamed, so they match the FiraCousine name?

**Comment by macduy** [comment]
Thanks for the comment. I'll update tomorrow.

**Comment by macduy** [comment]
Updated, PTAL and let me know if it works for you

**Comment by litera** [comment]
@macduy Unfortunately the added couple of italics aren't as they should've been, because they still have the names **Cousine** but should be named **Liga Fira Cousine** instead.

This issue should be reopened and resolved.

**Comment by macduy** [comment]
Updated the fonts, but sadly turns out Fira Code does not have italics... I found https://github.com/Avi-D-coder/fira-mono-italic but that does not have the ligatures.

I updated this repo with Italics versions of Cousine spliced with ligatures from Fira Code Regular. I'm not sure if the result will be aesthetically pleasing. Let me know how you get along.

**Comment by litera** [comment]
It's perfectly fine if the Italic version doesn't have italicised ligatures. Developers mostly use italics for comments so they're not that relevant codewise. **But**... The problem I pointed out wasn't really related to non-italic ligatures but rather to invalid font names... And this problem is still present in your latest commit.
If I open one of the italic font files, they still have the wrong name (just **Cousine**). Installing them would then overwrite actual Cousine despite having a different file name. The correct name should be **Liga Fira Cousine** the same as regular and bold versions have. This way they would belong to the correct font family. So far, they don't.

It also seems that your last commit was done 13 days ago, so the italic versions are still as they were. Maybe you forgot to push the italics you talk about in your last comment.

**Comment by macduy** [comment]
Yes I forgot to push. Let me do that in a bit

**Comment by macduy** [comment]
Pushed. The font name should now be `Fira Cousine`.

**Comment by litera** [comment]
Perfect! Thanks.
